services:
  - type: web
    name: smart-study-assistant-9u6m
    runtime: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DISABLE_HISTORY
        value: true
      - key: PYTHON_VERSION
        value: 3.11.9
